language: node_js
node_js:
  - "6"
  - "4"
before_script:
  - git clone --depth 1 https://github.com/APIs-guru/openapi-directory.git
  - git clone --depth 1 https://github.com/mermade/openapi_specifications.git
script:
  - node testRunner openapi-directory/
  - node testRunner openapi_specifications/
